/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./templates/**/*.html",
    "./templates/*.html"
  ],
  safelist: [
    'bg-blue-500',
    'bg-gray-50',
    'text-gray-800',
    'text-white',
    'p-4',
    'text-center',
    'bg-gray-800',
    'max-w-4xl',
    'mx-auto',
    'flex',
    'items-center',
    'space-x-4',
    'h-10',
    'text-2xl',
    'font-bold',
    'bg-gray-700',
    'hover:text-blue-400',
    'p-6',
    'bg-white',
    'rounded',
    'shadow',
    'mb-6',
    'text-xl',
    'font-semibold',
    'mb-2',
    'mb-4',
    'text-gray-500',
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}
